### ISSUE TITLE
Allow changing sign-in/register form header value

### ISSUE THREAD

**Issue by mehulgogri** [jenkinsci/login-theme-plugin#51]
### What feature do you want to see added?

By default, the sign-in/register form header is "Sign in to Jenkins".
We should allow the user to change this header value from the Jenkins system configuration page.

Example:
Sign in to Production Jenkins
Sign in to Staging Jenkins
Sign in to Company ABC's Sandbox Jenkins

**Comment by haker146** [comment]
Exactly, I also miss this functionality to remove the main title or simply change it, is there any solution for this?

**Comment by userAdityaa** [comment]
Hello, I think this is a good feature. But where can I find the file necessary for me to change this feature. Can you help me with this ?

**Comment by jonesbusy** [comment]
It's not possible : https://github.com/jenkinsci/jenkins/blob/jenkins-2.440.3/core/src/main/resources/jenkins/model/Jenkins/login.jelly#L73

This has nothing to do with login-theme-plugin. It's simply not possible due to jenkins core.

I will close this issue because there is nothing we can do here.

You should probably open an improvement on https://issues.jenkins.io/

Thanks
